### ISSUE TITLE
Puddles possibly causing server crash while raining

### ISSUE THREAD

**Issue by varencilator** [TeamMidnightDust/Puddles#5] opened 2021-05-07 21:36 UTC
According to:
https://github.com/malte0811/FerriteCore/issues/17#issue-879633037

I noticed it happens when it's raining so I believe it may be the issue. Happened even after I removed Ferritecore and Hydrogen mod.

**Comment by Motschen** [comment] 2021-05-08 08:14
Could you try setting both the snowStackChance and puddleSpawnRate gamerule to 0 and see if it still crashes?

**Comment by varencilator** [comment] 2021-05-08 18:59
How do I do that? I don't seem to have a config file. Also, for more info, it didn't seem to always crash the server when it rained, only recently when a player was online and it was raining. Puddles was working totally fine with all the mods for over a week.

**Comment by Motschen** [comment] 2021-05-08 20:10
> Puddles was working totally fine with all the mods for over a week.

That's weird, did you add any new mods after that?

**Comment by varencilator** [comment] 2021-05-09 19:49
The most recent mod I had added was randompatches but that was 5 days before I started having the problem so it's pretty hard to figure out the issue. I'll try changing the gamerule and seeing what's up.

**Comment by malte0811** [comment] 2021-05-12 06:53
I don't think this is a mod interaction: The problematic code section is [this](https://github.com/TeamMidnightDust/Puddles/blob/0342b5f3128a2ce5a545f47e0c170ce863d8af9e/src/main/java/eu/midnightdust/puddles/mixin/MixinServerWorld.java#L54-L58). If `getSurface` returns the position of a "full" snow block (8 layers) you still try to add an additional layer to it, which isn't possible. That would also explain why it only started happening after some time, it would take some time for enough snow to accumulate.

Somewhat related, it would be nice if you could either change the name of the method to indicate what mod it comes from or alternatively move the actual code to a different class and only have a call to that method in the mixin itself. Right now crashes inside that Mixin produce very cryptic stacktraces (see the original issue for an example), where the only way of finding the cause is to search for Mixins into that method calling `with` on github (and hoping that the mod is actually available there).

**Comment by Motschen** [comment] 2021-05-12 08:12
Thank you very much @malte0811 that explains a lot to me. I'll make sure to get a new version out soon.

**Comment by Motschen** [comment] 2021-05-12 09:09
Fixed in v1.1.0 :)

**Closed by Motschen** 2021-05-12 09:09 UTC
